name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --version

      - name: Run lint check
        run: make lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-version:
          - stable
          - nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Show Neovim version
        run: nvim --version

      - name: Run tests
        run: make test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.nvim-version }}
          path: /tmp/yoda_test_output.txt
          if-no-files-found: warn

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: All checks passed
        run: echo "✅ All CI checks passed!"

